// <auto-generated />
using System;
using BoookingRoomUniversity.Assignment.Repositories.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoookingRoomUniversity.Assignment.Repositories.Migrations
{
    [DbContext(typeof(BookingRoomUniversityDbContext))]
    [Migration("20250401071754_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.BookingCancel", b =>
                {
                    b.Property<int>("BookingCancelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingCancelId"));

                    b.Property<int>("BookingDetailId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingCancelId");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingCancel");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.BookingDetail", b =>
                {
                    b.Property<int>("BookingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDetailId"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BookingDetailId");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusId"));

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CampusId");

                    b.ToTable("Campuses");

                    b.HasData(
                        new
                        {
                            CampusId = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3759), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Khu Công Nghệ Cao, Quận 9, TP.HCM",
                            Name = "FPT University Hồ Chí Minh"
                        },
                        new
                        {
                            CampusId = 2,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3791), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Hòa Lạc, Thạch Thất, Hà Nội",
                            Name = "FPT University Hà Nội"
                        },
                        new
                        {
                            CampusId = 3,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3793), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Quận Ninh Kiều, TP. Cần Thơ",
                            Name = "FPT University Cần Thơ"
                        },
                        new
                        {
                            CampusId = 4,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3794), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Ngũ Hành Sơn, TP. Đà Nẵng",
                            Name = "FPT University Đà Nẵng"
                        },
                        new
                        {
                            CampusId = 5,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3796), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Khu Đô thị Khoa học Quy Hòa, TP. Quy Nhơn",
                            Name = "FPT University Quy Nhơn"
                        });
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepartmentId");

                    b.HasIndex("CampusId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CampusId = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3971), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Software Development Department",
                            Name = "Software Engineering"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CampusId = 2,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3976), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Business & Marketing Department",
                            Name = "Business Administration"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CampusId = 3,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3977), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "AI Research Department",
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            DepartmentId = 4,
                            CampusId = 4,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3979), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Cyber Security Department",
                            Name = "Cyber Security"
                        },
                        new
                        {
                            DepartmentId = 5,
                            CampusId = 5,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(3981), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Data Analytics Department",
                            Name = "Data Science"
                        });
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RoomId");

                    b.HasIndex("CampusId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            CampusId = 1,
                            Capacity = 50,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(4003), new TimeSpan(0, 7, 0, 0, 0)),
                            Name = "Room A101",
                            Status = 0
                        },
                        new
                        {
                            RoomId = 2,
                            CampusId = 2,
                            Capacity = 30,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(4006), new TimeSpan(0, 7, 0, 0, 0)),
                            Name = "Room B202",
                            Status = 2
                        },
                        new
                        {
                            RoomId = 3,
                            CampusId = 3,
                            Capacity = 40,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(4008), new TimeSpan(0, 7, 0, 0, 0)),
                            Name = "Room C303",
                            Status = 0
                        },
                        new
                        {
                            RoomId = 4,
                            CampusId = 4,
                            Capacity = 20,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(4010), new TimeSpan(0, 7, 0, 0, 0)),
                            Name = "Room D404",
                            Status = 0
                        },
                        new
                        {
                            RoomId = 5,
                            CampusId = 5,
                            Capacity = 60,
                            CreatedTime = new DateTimeOffset(new DateTime(2025, 4, 1, 14, 17, 54, 561, DateTimeKind.Unspecified).AddTicks(4012), new TimeSpan(0, 7, 0, 0, 0)),
                            Name = "Room E505",
                            Status = 0
                        });
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.RoomDetail", b =>
                {
                    b.Property<int>("RoomDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomDetailId"));

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RoomDetailId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SlotId");

                    b.ToTable("RoomDetail");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Slot", b =>
                {
                    b.Property<int>("SLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLotId"));

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SLotId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId");

                    b.HasIndex("CampusId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Booking", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.BookingCancel", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.BookingDetail", "BookingDetail")
                        .WithMany("BookingCancels")
                        .HasForeignKey("BookingDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Booking", "Booking")
                        .WithMany("BookingCancels")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.User", "User")
                        .WithMany("BookingCancels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("BookingDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.BookingDetail", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", "Campus")
                        .WithMany("Departments")
                        .HasForeignKey("CampusId");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", "Campus")
                        .WithMany("Rooms")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.RoomDetail", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", "Room")
                        .WithMany("RoomDetails")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Slot", "Slot")
                        .WithMany("RoomDetails")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.User", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", null)
                        .WithMany("Users")
                        .HasForeignKey("CampusId");

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Booking", b =>
                {
                    b.Navigation("BookingCancels");

                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.BookingDetail", b =>
                {
                    b.Navigation("BookingCancels");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("RoomDetails");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Slot", b =>
                {
                    b.Navigation("RoomDetails");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.User", b =>
                {
                    b.Navigation("BookingCancels");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
