// <auto-generated />
using System;
using BoookingRoomUniversity.Assignment.Repositories.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoookingRoomUniversity.Assignment.Repositories.Migrations
{
    [DbContext(typeof(BookingRoomUniversityDbContext))]
    partial class BookingRoomUniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusId"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CampusId");

                    b.ToTable("Campuses");

                    b.HasData(
                        new
                        {
                            CampusId = 1,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9283),
                            Location = "Khu Công Nghệ Cao, Quận 9, TP.HCM",
                            Name = "FPT University Hồ Chí Minh"
                        },
                        new
                        {
                            CampusId = 2,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9299),
                            Location = "Hòa Lạc, Thạch Thất, Hà Nội",
                            Name = "FPT University Hà Nội"
                        },
                        new
                        {
                            CampusId = 3,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9301),
                            Location = "Quận Ninh Kiều, TP. Cần Thơ",
                            Name = "FPT University Cần Thơ"
                        },
                        new
                        {
                            CampusId = 4,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9302),
                            Location = "Ngũ Hành Sơn, TP. Đà Nẵng",
                            Name = "FPT University Đà Nẵng"
                        },
                        new
                        {
                            CampusId = 5,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9303),
                            Location = "Khu Đô thị Khoa học Quy Hòa, TP. Quy Nhơn",
                            Name = "FPT University Quy Nhơn"
                        });
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.HasIndex("CampusId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CampusId = 1,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9416),
                            Description = "Software Development Department",
                            Name = "Software Engineering",
                            Status = 1
                        },
                        new
                        {
                            DepartmentId = 2,
                            CampusId = 2,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9418),
                            Description = "Business & Marketing Department",
                            Name = "Business Administration",
                            Status = 1
                        },
                        new
                        {
                            DepartmentId = 3,
                            CampusId = 3,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9420),
                            Description = "AI Research Department",
                            Name = "Artificial Intelligence",
                            Status = 1
                        },
                        new
                        {
                            DepartmentId = 4,
                            CampusId = 4,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9422),
                            Description = "Cyber Security Department",
                            Name = "Cyber Security",
                            Status = 1
                        },
                        new
                        {
                            DepartmentId = 5,
                            CampusId = 5,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9423),
                            Description = "Data Analytics Department",
                            Name = "Data Science",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId");

                    b.HasIndex("CampusId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            CampusId = 1,
                            Capacity = 50,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9471),
                            Description = "Lecture Hall",
                            Name = "Room A101",
                            Status = 0
                        },
                        new
                        {
                            RoomId = 2,
                            CampusId = 2,
                            Capacity = 30,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9475),
                            Description = "Computer Lab",
                            Name = "Room B202",
                            Status = 0
                        },
                        new
                        {
                            RoomId = 3,
                            CampusId = 3,
                            Capacity = 40,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9476),
                            Description = "Seminar Room",
                            Name = "Room C303",
                            Status = 1
                        },
                        new
                        {
                            RoomId = 4,
                            CampusId = 4,
                            Capacity = 20,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9478),
                            Description = "Meeting Room",
                            Name = "Room D404",
                            Status = 1
                        },
                        new
                        {
                            RoomId = 5,
                            CampusId = 5,
                            Capacity = 60,
                            CreatedTime = new DateTime(2025, 3, 27, 18, 31, 21, 171, DateTimeKind.Local).AddTicks(9480),
                            Description = "Conference Hall",
                            Name = "Room E505",
                            Status = 0
                        });
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.Property<int>("RoomsRoomId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("RoomsRoomId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("RoomUser");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Booking", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", "Campus")
                        .WithMany("Departments")
                        .HasForeignKey("CampusId");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", "Campus")
                        .WithMany("Rooms")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.User", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoookingRoomUniversity.Assignment.Repositories.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Campus", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BoookingRoomUniversity.Assignment.Repositories.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
